security:
    acl:
        connection: default

    role_hierarchy:
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            entity:
                class:    AppBundle\Entity\User
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        AppBundle\Entity\User: sha512

    firewalls:

        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider:  in_memory
            form_login:
                login_path: security_login
                check_path: security_login_check
                default_target_path: computer
                always_use_default_target_path: true
            logout:
                path:   security_logout
                target: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_(profiler|wdt)|css|images|js)/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_REMEMBERED }


